'use strict';

let { gt } = window;

gt.locale = {
  translate: function (obj) {
    if (!obj) {
      return obj;
    }
    if (typeof obj === 'string' && !gt.locale.cn.hasOwnProperty(obj)) {
      gt.locale.unlocalized[obj] = obj;
      return obj;
    }
    if (typeof obj === 'string') {
      return gt.locale.cn[obj];
    }
    if (Array.isArray(obj)) {
      return obj.map(gt.locale.translate);
    }
    return obj;
  },
  unlocalized: {},
  cn: Object.assign({}, ...Object.values({
    ui: {
      "Search": "搜索",
      "Patches": "版本",
      "2.0": "2.0",
      "3.0": "3.0",
      "4.0": "4.0",
      "Classes": "职业",
      "Mining": "采矿工",
      "Botany": "园艺工",
      "Fishing": "捕鱼人",
      "Types": "类型",
      "Unspoiled": "未知的采集点",
      "Ephemeral": "限时的采集点",
      "Legendary": "传说的采集点",
      "Tasks": "目的",
      "Collectable": "收藏品",
      "Reducible": "精选",
      "Red Scrips": "红票",
      "Yellow Scrips": "黄票",
      "Hidden": "已隐藏",
      "Other": "其他",
      "Gold S.": "金碟",
      "Hunt": "狩猎",
      "timers": "个定时事件",
      'hidden': '个已隐藏',

      "Audio notifications are blocked by your browser.  Garland Bell will be unable to sound alerts.": "您的浏览器阻止了音频通知，Garland Bell 将无法播放提醒铃声。",
      "Dismiss.": "哦。",
      "Audio preloading is not supported by your browser.  The first notification you receive may not play properly.": "您的浏览器不支持音频预加载，第一次的铃声可能无法正常播放。",
      "Popup notifications can not be displayed.": "无法显示弹出式通知。",
      "Local storage is blocked by your browser.  You may be in private browsing mode.  Changes will not be saved.": "您的浏览器阻止了本地储存，您可能正在使用隐身浏览模式，设置将不会被储存。",

      "Rotations": "手法",
      "Timeline": "时间轴",
      "Maps": "地图",
      "Timers": "定时事件",

      "Select a list for this timer": "选择存放此定时事件的列表",
      "Name the new list": "新列表的名字",
      "Completed": "已完成",
      "Favorites": "收藏夹",
      "Create new list": "新建列表",
      "A list with this name already exists.": "已存在此名字的列表。",
      "Remove from list?  Click again to confirm.": "从列表中删除? 再次点击确认。",

      "Freshwater Fishing": "淡水",
      "Skyfishing": "空鱼",
      "Cloudfishing": "云海",
      "Ocean Fishing": "海水",
      "Dunefishing": "沙海",
      "Rocky Outcropping": "石场",
      "Mineral Deposit": "矿脉",
      "Mature Tree": "良材",
      "Lush Vegetation": "草场",

      "Aetherial Reduction possible": "可精选",
      "Blue Gatherers' Scrip": "蓝票收藏品",
      "Red Gatherers' Scrip": "红票收藏品",
      "Yellow Gatherers' Scrip": "黄票收藏品",
      "Perception": "鉴别力",
      "Gathering": "获得力",
      " Gathering Rate": "获得率",
      " Gathering Fortune": "优质率",
      "mooch": "以小钓大",
      "Predator": "捕鱼人之识",
    },
    settings: {
      "Settings": "设置",
      "Early Warning Alarm": "预提醒铃声",
      "Spawn Alarm": "进窗口铃声",
      "Linkshell": "通讯贝",
      "Tell 1": "铃声1",
      "Tell 2": "铃声2",
      "Tell 3": "铃声3",
      "Alarm tone to sound for favorite nodes.": "选择你喜欢的提醒铃声。",
      "Early Warning Volume": "预提醒音量",
      "Spawn Volume": "进窗口音量",
      "Volume of the alarm.": "铃声的音量。",
      "Early Warning Time": "预提醒提前时间",
      "Spawn Time": "进窗口提前时间",
      "Wait this number of real seconds before sounding the alarm.": "提前多少秒播放铃声。",
      "Unlimited Columns": "不限制列数",
      "Use as many columns as possible.": "显示尽可能多的列。",
      "Compact": "紧凑模式",
      "Compact timer information to the essentials.": "定时事件中只显示关键信息。",
      "Colorblind": "色盲模式",
      "Alter active bar colors to better suit colorblind users.": "调整着色以适合色盲用户。",
      "Server Time": "服务器时间",
      "Calibrate time with the server.  Use if your time is wrong.": "校准至服务器时间，适用于本地时间不准的情况。",
    },
    rotations: {},
    zones: {
      "Limsa Lominsa": "利姆萨・罗敏萨",
      "Middle La Noscea": "中拉诺西亚",
      "Lower La Noscea": "拉诺西亚低地",
      "Eastern La Noscea": "东拉诺西亚",
      "Western La Noscea": "西拉诺西亚",
      "Upper La Noscea": "拉诺西亚高地",
      "Outer La Noscea": "拉诺西亚外地",
      "Mist": "海雾村",
      "Gridania": "格里达尼亚",
      "Central Shroud": "黑衣森林中央林区",
      "East Shroud": "黑衣森林东部林区",
      "South Shroud": "黑衣森林南部林区",
      "North Shroud": "黑衣森林北部林区",
      "The Lavender Beds": "薰衣草苗圃",
      "Ul'dah": "乌尔达哈",
      "Western Thanalan": "西萨纳兰",
      "Central Thanalan": "中萨纳兰",
      "Eastern Thanalan": "东萨纳兰",
      "Southern Thanalan": "南萨纳兰",
      "Northern Thanalan": "北萨纳兰",
      "The Goblet": "高脚孤丘",
      "Ishgard": "伊修加德",
      "Coerthas Central Highlands": "库尔札斯中央高地",
      "Coerthas Western Highlands": "库尔札斯西部高地",
      "Mor Dhona": "摩杜纳",
      "The Sea of Clouds": "阿巴拉提亚云海",
      "Azys Lla": "魔大陆阿济兹拉",
      "The Dravanian Forelands": "龙堡参天高地",
      "The Dravanian Hinterlands": "龙堡内陆低地",
      "The Churning Mists": "翻云雾海",
      "Idyllshire": "田园郡",
      "Rhalgr's Reach": "神拳痕",
      "The Fringes": "基拉巴尼亚边区",
      "The Peaks": "基拉巴尼亚山区",
      "The Lochs": "基拉巴尼亚湖区",
      "Kugane": "黄金港",
      "Shirogane": "白银乡",
      "The Ruby Sea": "红玉海",
      "Yanxia": "延夏",
      "The Azim Steppe": "太阳神草原",
    },
    areas: {
      "The Tangle": "纠缠沼泽林",
      "Eli Tohm": "招恶荒岛",
      "Dragonspit": "龙涎",
      "Vundu Ok' Bendu": "温杜属本杜集落",
      "The Ruling Quarter": "萨雷安睿哲区",
      "Mother of the Sheave": "圣女希瓦像",
      "The Lost Landlord": "人王像",
      "Beta Quadrant": "贝塔管区",
      "The Convictory": "圣菲内雅连队露营地",
      "The Answering Quarter": "萨雷安治学区",
      "The Nidifice": "候鸟云巢",
      "Habisphere Control": "生态园管理局",
      "Alpha Quadrant": "阿尔法管区",
      "The Gauntlet": "试炼群岛",
      "The Watcher": "守望者",
      "The Bed of Bones": "大脚雪人居所",
      "Hemlock": "铁杉村",
      "Twinpools": "双子池",
      "The Blue Window": "蓝天窗",
      "Avalonia Fallen": "阿瓦隆尼亚古陆",
      "Four Arms": "四臂广场",
      "The Makers' Quarter": "萨雷安精制区",
      "Upper Thaliak River": "沙利亚克河上流",
      "Clearpool": "清澈池",
      "The Pappus Tree": "冠毛大树",
      "Weston Waters": "西方水泉",
      "The Smoldering Wastes": "荒烟野地",
      "Whilom River": "宽慰河",
      "Tharl Oom Khash": "惋惜之晶遗迹",
      "The Iron Feast": "饵食台地",
      "Sohm Al Summit": "索姆阿尔峰顶",
      "Middle Thaliak River": "沙利亚克河中流",
      "The Habisphere": "生态园",
      "The Hundred Throes": "悲叹飞泉",
      "Black Iron Bridge": "黑铁大桥",
      "Loth ast Vath": "荒烟野地",
      "Chocobo Forest": "陆行鸟之森",
      "Landlord Colony": "人王遗迹",
      "Red Rim": "红沿",
      "Voor Sian Siran": "沃仙曦染",
      "The House of Letters": "书信之家",
      "Easton Eyes": "东方眼目",
      "Coldwind": "寒风岛",
      "The Daggers": "萨雷安睿哲区",
      "North Silvertear": "银泪湖北岸",
      "The North Shards": "歌咏裂谷北部",
      "Whitebrim": "白云崖",
      "Providence Point": "神意之地",
      "Dragonhead": "巨龙首",
      "Witchdrop": "落魔崖",
      "Raubahn's Push": "劳班缓冲地",
      "Yugr'am River": "宇格拉姆河",
      "Bluefog": "蓝雾",
      "Broken Water": "秽水",
      "Drybone": "枯骨",
      "Burgundy Falls": "紫红瀑布",
      "Wellwick Wood": "新植林",
      "Haldrath's March": "哈尔德拉斯行军道",
      "Lost Hope": "无望流民街",
      "Hammerlea": "金锤台地",
      "Sagolii Desert": "撒沟厉沙海",
      "Moraby Bay": "莫拉比湾",
      "Raincatcher Gully": "接雨草树林",
      "Zephyr Drift": "和风流地",
      "Quarterstone": "四分石地",
      "Bronze Lake": "石绿湖",
      "Summerford": "盛夏农庄",
      "Bloodshore": "鲜血滨",
      "Cedarwood": "雪松原",
      "Isles of Umbra Southshore": "幻影群岛南岸",
      "Rhotano Sea (Privateer Sterncastle)": "罗塔诺海（船尾）",
      "Bentbranch": "弯枝",
      "Rootslake": "蔓根沼",
      "Upper Paths": "高径",
      "Urth's Gift": "兀尔德恩惠地",
      "Naked Rock": "裸岩丘",
      "Nine Ivies": "九藤",
      "The Honey Yard": "蜜场",
      "Little Solace": "妖精暂留地",
      "Sorrel Haven": "酸模避风港",
      "Alder Springs": "桤木泉",
      "The Bramble Patch": "荆棘森",
      "The Flagship": "阿济兹拉旗舰岛",
      "Aetherfishing": "魔泉",
      "Hengr's Crucible": "亨格坩埚",
      "Eil Tohm": "招恶荒岛",
      "Sothton Walls": "南方墙壁",
      "Mourn": "彻悟岩窟",
      "Antithesis": "对偶处刑台",
      "Greensward": "绿茵岛",
      "Rathefrost": "早霜顶",
      "Zahar'ak": "不悔战泉",
      "Moondrip": "月滴洞",
      "Everschade": "常影区",
      "Goblinblood": "哥布林血流",
      "Swiftperch": "雨燕塔殖民地",
      "Oakwood": "橡树原",
      "Halfstone": "二分石沿岸地",
      "Snowcloak": "披雪大冰壁",
      "Sylphlands": "妖精领溪谷",
      "Cloudtop": "旋风云海",
      "Halo": "光轮祭坛",
      "Riversmeet": "交汇河营地",
      "Mok Oogl Island": "魔窟离岛",
      "Moraby Drydocks": "莫拉比造船厂",
      "Hyperstellar Downconverter": "超星际通信塔",
      "Quickspill Delta": "湍流三角地",
      "Forgotten Springs": "遗忘绿洲",
      "North Drybone": "枯骨北泉",
      "Lower Hathoeva River": "哈希瓦河下游",
      "Costa del Sol": "太阳海岸",
      "Empty Heart": "空心穴",
      "Sagolii Dunes": "撒沟厉沙丘",
      "Proud Creek": "荣耀溪",
      "North Bloodshore": "北鲜血滨",
      "Verdant Drop": "落翠底",
      "The Salt Strand": "砂盐滩",
      "Upper Hathoeva River": "哈希瓦河上游",
      "South Drybone": "枯骨南泉",
      "Sanctum of the Twelve": "十二神大圣堂",
      "The Clutch": "执掌峡谷",
      "East Agelyss River": "东永恒川",
      "Parata's Peace": "帕拉塔安息地",
      "The Long Climb": "登天路溪谷",
      "Blind Iron Mines": "盲铁坑道",
      "Burnt Lizard Creek": "火蜥蜴河",
      "Nophica's Wells": "丰饶神井",
      "Upper Black Tea Brook": "红茶川水系上游",
      "Sea of Clouds": "伊修加德大云海",
      "The Burning Wall": "火墙",
      "Exploratory Ice Hole": "调查队冰洞",
      "Hidden Falls": "隐秘瀑布",
      "The Nail": "剑峰山麓",
      "Fool Falls": "愚者瀑布",
      "Limsa Lominsa Lower Decks": "利姆萨·罗敏萨下层甲板",
      "Isles of Umbra Northshore": "幻影群岛北岸",
      "Coerthas River": "库尔札斯河",
      "Sapsa Spawning Grounds": "萨普沙产卵地",
      "Dragonhead Latrines": "巨龙首营地水库",
      "Springripple Brook": "涟漪小川",
      "The Weeping Saint": "圣人泪",
      "The Ship Graveyard": "船舶墓场",
      "Jadeite Flood": "翡翠湖滨",
      "Oschon's Torch": "奥修昂火炬",
      "Nym River": "尼姆河",
      "The Footfalls": "足迹谷",
      "Middle Hathoeva River": "哈希瓦河中游",
      "Whispering Gorge": "低语河谷",
      "Murmur Rills": "嘈杂川",
      "Sweetbloom Pier": "花蜜栈桥",
      "Singing Shards": "歌咏裂谷",
      "The Juggernaut": "接雨草沼泽地",
      "Rogue River": "无赖川",
      "The Mirror": "镜池",
      "The Silver Bazaar": "白银集市",
      "Daniffen Pass": "圣人旅道",
      "South Bloodshore": "南鲜血滨",
      "Hopeseed Pond": "萌芽池",
      "Bronze Lake Shallows": "石绿湖浅滩",
      "Limsa Lominsa Upper Decks": "利姆萨·罗敏萨上层甲板",
      "Skull Valley": "骷髅谷沿岸地",
      "Woad Whisper Canyon": "轻声谷",
      "Reaver Hide": "隐秘港",
      "Upper Soot Creek": "污流上游",
      "Crescent Cove": "月牙湾",
      "Fallgourd Float": "秋瓜湖畔",
      "The Brewer's Beacon": "酿酒师灯塔",
      "Lower Soot Creek": "污流下游",
      "Candlekeep Quay": "守炬埠头",
      "Haukke Manor": "名门府邸静语庄园",
      "Ceruleum Field": "青磷泉",
      "The Deep Tangle": "纠缠沼泽林源流",
      "Cape Westwind": "西风岬",
      "The Unholy Heir": "邪嗣",
      "Greytail Falls": "灰尾瀑布",
      "South Banepool": "灾祸池南",
      "The Eddies": "云水塘",
      "Delta Quadrant": "德尔塔管区",
      "Anyx Old": "不洁古像",
      "West Banepool": "灾祸池北",
      "West Mourn": "彻悟岩窟西",
      "Rhotano Sea (Privateer Forecastle)": "罗塔诺海（船首）",
      "Unfrozen Pond": "库尔札斯不冻池",

      "The Striped Hills": "条纹丘",
      "Rustrock": "红锈岩山",
      "Ten-thousand-year Pine": "万年松",
      "Valley of the Fallen Rainbow": "七彩溪谷",
      "The Towering Still": "挡风巨岩",
      "Wightrock": "白鬼岩山",
      "Monzen": "门前卫街",
      "Loch Seld": "盐湖",
      "Unseen Spirits Laughing": "祖灵笑",
      "Onsal Hakair": "昂萨哈凯尔",
      "The High Bank": "高岸",
      "East End": "东境混交林",
      "Kusakari": "草刈家",
      "Ceol Aen": "乔尔艾恩石环",
      "The Royal Hunting Grounds": "王家猎场",
      "Stacks": "柴堆村",
      "Doma": "多玛",
      "Nhaama's Retreat": "月神沙漠北端",
      "Abalathia's Skull": "阿巴拉提亚龙头",

      "Northeast Bronze Lake": "Northeast Bronze Lake",
      "Hellfishing": "Hellfishing",
      "North Isle of Endless Summer": "North Isle of Endless Summer",
      "Upper Mirage Creek": "Upper Mirage Creek",
      "Dimwold": "昏暗林",
      "The Comet's Tail": "The Comet's Tail",
      "Heather Falls": "Heather Falls",
      "The Ephor": "The Ephor",
      "The Bull's Bath": "The Bull's Bath",
      "The Arms of Meed": "The Arms of Meed",
      "Eastern Pike": "Eastern Pike",
      "Sculptor": "Sculptor",
      "Saltfishing": "Saltfishing",
      "Hells' Lid": "Hells' Lid",
      "The Isle of Bekko": "The Isle of Bekko",
      "Onokoro": "Onokoro",
      "The One River (East)": "The One River (East)",
      "The One River (West)": "The One River (West)",
      "Plum Spring": "Plum Spring",
      "Mercantile Docks": "Mercantile Docks",
      "Doma Castle": "Doma Castle",
      "Nem Khaal": "Nem Khaal",
      "Hak Khaal": "Hak Khaal",
      "Kugane Piers": "Kugane Piers",
    },
    weathers: {
      "Clouds": "阴云",
      "Clear Skies": "碧空",
      "Fair Skies": "晴朗",
      "Fog": "薄雾",
      "Rain": "小雨",
      "Wind": "微风",
      "Showers": "暴雨",
      "Gales": "强风",
      "Thunder": "打雷",
      "Thunderstorms": "雷雨",
      "Dust Storms": "扬沙",
      "Heat Waves": "热浪",
      "Gloom": "妖雾",
      "Snow": "小雪",
      "Blizzards": "暴雪",
      "Umbral Wind": "灵风",
      "Umbral Static": "灵电",
    },
    items: {
      "Yellow Copper Ore": "黄铜矿",
      "Chives": "库尔札斯青葱",
      "Pearl Sprouts": "小包心菜",
      "Coerthan Tea Leaves": "库尔札斯茶叶",
      "Pearl Sprout Seeds": "小包心菜种子",
      "Coerthan Tea Seeds": "库尔札斯茶叶种子",
      "Chalcocite": "辉铜矿",
      "Pyrite": "黄铁矿",
      "Limonite": "褐铁矿",
      "Old World Fig": "旧世界无花果",
      "Old World Fig Seeds": "旧世界无花果种子",
      "Fire Moraine": "火砂砾",
      "Bright Fire Rock": "强火性岩",
      "Radiant Fire Moraine": "火光砾",
      "Chysahl Greens": "卡贝基野菜",
      "Granular Clay": "赤玉土",
      "Peat Moss": "灰玉土",
      "Black Soil": "黑土",
      "Lightning Moraine": "雷砂砾",
      "Radiant Lightning Moraine": "强雷性岩",
      "Bright Lightning Rock": "雷光砾",
      "Highland Oregano": "牛至",
      "Furymint": "留兰",
      "Clary Sage": "鼠尾草",
      "Yellow Quartz": "土黄石英",
      "Green Quartz": "翠绿石英",
      "Dravanian Mistletoe": "龙堡槲寄生",
      "Porcini": "牛肝菌",
      "Adamantite Ore": "精金矿",
      "Heavens Lemon": "伊修加德柠檬",
      "Abalathian Mistletoe": "阿巴拉提亚槲寄生",
      "Abalathian Rock Salt": "阿巴拉提亚岩盐",
      "Red Quartz": "深绯石英",
      "Cloud Banana": "云海香蕉",
      "Morel": "伞蘑",
      "Cuprite": "赤铜矿",
      "Light Kidney Ore": "赤铁矿",
      "Aurum Regis Ore": "皇金矿",
      "Astral Moraine": "星砂砾",
      "Violet Quartz": "青紫石英",
      "Blue Quartz": "绀碧石英",
      "Red Alumen": "红明矾",
      "Seventh Heaven": "星极花",
      "Honeydew Almonds": "甜扁桃",
      "Vanilla Beans": "香草豆",
      "Snurbleberry": "鲜红罗兰莓",
      "Wattle Bark": "金合欢树皮",
      "Dravanian Paprika": "翻云雾海红辣椒",
      "Sun Mica": "金云母",
      "Grade 4 Carbonized Matter": "4级碳化暗物质",
      "Lightning Cluster": "雷之晶簇",
      "Fire Cluster": "火之晶簇",
      "Wind Cluster": "风之晶簇",
      "Water Cluster": "水之晶簇",
      "Ice Cluster": "冰之晶簇",
      "Earth Cluster": "土之晶簇",
      "Unaspected Crystal": "无属性水晶",
      "Dark Matter Cluster": "暗物质晶簇",
      "Thavnairian Mistletoe": "萨维奈槲寄生",
      "Spruce Log": "云杉原木",
      "Astral Rock": "星性岩",
      "Vampire Plant": "吸血枝",
      "Ferberite": "钨铁矿",
      "Raw Topaz": "黄玉原石",
      "Raw Iolite": "堇青石原石",
      "Gold Sand": "金沙",
      "Virgin Basilisk Egg": "石蜥蜴的初蛋",
      "Platinum Ore": "白金矿",
      "Mazlaya Greens": "马兹拉雅草",
      "Black Truffle": "黑松露",
      "Gold Ore": "金矿",
      "Coblyn Larva": "矿爬虫虫",
      "Gregarious Worm": "群居蠕虫",
      "Antumbral Rock": "强灵性岩",
      "Darksteel Ore": "玄铁矿",
      "Native Gold": "自然金",
      "Raw Emerald": "祖母绿原石",
      "Raw Diamond": "钻石原石",
      "Grade 3 Thanalan Topsoil": "3级萨纳兰土壤",
      "Raw Ruby": "红宝石原石",
      "Raw Sapphire": "蓝宝石原石",
      "Pumice": "浮石",
      "Dzemael Tomato Seeds": "泽梅尔番茄种子",
      "Dzemael Tomato": "泽梅尔番茄",
      "Volcanic Rock Salt": "拉诺西亚岩盐",
      "Ebony Log": "黑檀原木",
      "Grade 3 La Noscean Topsoil": "3级拉诺西亚土壤",
      "La Noscean Leek": "拉诺西亚韭菜",
      "Waterfowl Feather": "水鸟之羽",
      "Blood Orange": "鲜血橙",
      "Bamboo Stick": "竹材",
      "Apricot": "黄杏",
      "Prickly Pineapple Seeds": "多刺菠萝种子",
      "Prickly Pineapple": "多刺菠萝",
      "Honey Lemon Seeds": "蜜柠檬种子",
      "Honey Lemon": "蜜柠檬",
      "Young Cieldalaes Spinach": "谢尔达莱嫩菠菜",
      "Trillium": "延龄花",
      "Scarlet Sap": "绯红树汁",
      "Shroud Tea Leaves": "提诺尔卡茶叶",
      "Silkworm Cocoon": "蚕茧",
      "Kidragora": "小小蔓德拉",
      "Trillium Bulb": "延龄草的球根",
      "Redolent Log": "高级黑衣香木",
      "Rosemary": "迷迭香",
      "Fragrant Log": "黑衣香木",
      "Umbral Rock": "灵性岩",
      "Grade 3 Shroud Topsoil": "3级黑衣森林土壤",
      "Cypress Log": "丝柏原木",
      "Frost Cotton Boll": "雪棉",
      "Smithsonite Ore": "菱锌矿",
      "Old-growth Camphorwood Log": "樟木古树",
      "Lumythrite Ore": "光银矿",
      "Lover's Laurel": "梅茵菲娜月桂",
      "Radiant Astral Moraine": "星光砾",
      "Luminium Ore": "辉金矿",
      "Zeolite Ore": "沸石",
      "Crystallized Sap": "树汁结晶",
      "Noble Sage": "显贵鼠尾草",

      "Raw Triphane": "锂辉石原石",
      "Pummelite": "硬拳石",
      "Raw Rhodonite": "蔷薇辉石原石",
      "Raw Star Spinel": "星尖石原石",
      "Raw Imperial Jade": "琅玕原石",
      "Raw Azurite": "石青原石",
      "Chromite Ore": "铬铁矿",
      "Palladium Ore": "钯金矿",
      "Ala Mhigan Salt Crystal": "阿拉米格盐",
      "Perlite": "珍珠岩",
      "Fire Crystal": "火之水晶",
      "Schorl": "黑碧玺",
      "Lightning Crystal": "雷之水晶",
      "Almandine": "贵榴石",
      "Ice Crystal": "冰之水晶",
      "Gyr Abanian Spring Water": "Gyr Abanian Spring Water",

      "Beech Branch": "山毛榉树枝",
      "Hallowed Basil": "祝圣罗勒草",
      "Bamboo Shoot": "竹笋",
      "Lotus Root": "莲藕",
      "Othardian Plum": "奥萨德梅",
      "Rhea": "苎麻",
      "Rhalgr's Streak": "破坏神之杖",
      "Jhammel Ginger": "长颈骆姜",
      "Torreya Log": "榧木原木",
      "Windtea Leaves": "风茶叶",
      "Wind Crystal": "风之水晶",
      "Doman Yellow": "黄土",
      "Earth Crystal": "土之水晶",
      "Torreya Branch": "榧树枝",
      "Azim Cotton Boll": "Azim Cotton Boll",
    },
    baits: {
      "Sand Leech": "沙蛭",
      "Storm Rider": "飞沙鱼",
      "Sky Faerie": "夕月天女",
      "Rudderfish": "高天鱼",
      "Blueclaw Shrimp": "蓝螯虾",
      "Hoverworm": "浮游虫",
      "Cloud Cutter": "破云飞鱼",
      "Mahar": "马哈尔",
      "Brute Leech": "残暴水蛭",
      "Red Balloon": "红气球虫",
      "Goblin Jig": "哥布林钓钩",
      "Stonefly Nymph": "石蝇幼虫",
      "Bladed Steel Jig": "叶片钓钩",
      "Bullfrog": "牛蛙",
      "Sweetfish": "香鱼",
      "Steel Jig": "铁板钩",
      "Fullmoon Sardine": "满月沙丁鱼",
      "Honey Worm": "蜜虫",
      "Silverfish": "银鱼",
      "Goldfish": "金鱼",
      "Assassin Betta": "暗斗鱼",
      "Glowworm": "火萤",
      "Topwater Frog": "漂浮诱饵蛙",
      "Northern Krill": "极地磷虾",
      "Giant Crane Fly": "巨蚊",
      "Butterworm": "黄油虫",
      "Wildfowl Fly": "雉鸡拟饵",
      "Ala Mhigan fighting fish": "斗鱼",
      "Brass Spoon Lure": "黄铜勺形鱼饵",
      "Salmon Roe": "鲑鱼籽",
      "Stonefly Larva": "嗡嗡石蝇",
      "Suspending Minnow": "悬浮米诺拟饵",
      "Midge Larva": "赤虫",
      "Silkworm": "蚕蛹",
      "Live Shrimp": "活虾",
    },
    fishs: {
      "Tupuxuara": "妖精翼龙",
      "Capelin": "毛鳞鱼",
      "Thunderbolt Eel": "落雷鳗",
      "Loosetongue": "哲学骨舌鱼",
      "Thaliak Caiman": "沙利亚克鳄",
      "Caiman": "凯门鳄",
      "Weston Bowfin": "西水弓鳍鱼",
      "Noontide Oscar": "白丽鱼",
      "Pipira Pira": "皮皮拉皮拉鱼",
      "Pteranodon": "无齿翼龙",
      "Warmwater Bichir": "多鳍鱼",
      "Tiny Axolotl": "小钝口螈",
      "Manasail": "魔帆",
      "Dravanian Bass": "龙堡鲈",
      "Kuno the Killer": "杀手库诺",
      "Canavan": "加诺",
      "Shonisaurus": "秀尼鱼龙",
      "Helicoprion": "旋齿鲨",
      "Little Thalaos": "小撒拉奥斯",
      "Endoceras": "内角石",
      "Nepto Dragon": "涅普特龙",
      "Namitaro": "波太郎",
      "Giant Takitaro": "大泷太郎",
      "Ninja Betta": "忍斗鱼",
      "Midge Basket": "摇蚊",
      "Fiend Worm": "恶魔蠕虫",
      "Platinum Fish": "白金鱼",
      "Barreleye": "桶眼鱼",
      "Spearnose": "枪鼻头",
      "Shadowstreak": "影纹狗鱼",
      "Ndendecki": "恩登德奇",
      "Bombardfish": "轰击泡",
      "Sylphsbane": "妖祸鱼",
      "Levinlight": "雷神光",
      "Thundergut": "吞雷鱼",
      "Twitchbeard": "抽须王",
      "Starbright": "星光鳟鱼",
      "Darkstar": "暗星",
      "Armorer": "铸甲专家之证",
      "Syldra": "希尔德拉",
      "Mirrorscale": "银镜鱼",
      "Fingers": "断指龙虾",
      "Bloodbath": "血浴",
      "Hannibal": "汉尼拔",
      "Vanuhead": "瓦努头",
      "Scaleripper": "龙鳞撕裂者",
      "Vidofnir": "维德弗尼尔",
      "Merciless": "冰之巫女",
      "Meteortoise": "巨陨龟",
      "Starflower": "星花",
      "Meteorite": "陨石",
      "Tungstite": "钨华",
      "Coelacanthus": "空棘鱼",
      "Spinner": "礼花“蔚蓝蜘蛛”",
      "Sweetnewt": "芳香蝾螈",
      "Discobolus": "铁饼",
      "Spinnerbait": "复合亮片",
      "Copperfish": "铜鱼",
      "Gigantshark": "巨鲨",
      "Lugworm": "沙蚕",
      "Bloodworm": "血蚯蚓",
      "Cupfish": "鱼大叔",
      "Anomalocaris": "奇虾",
      "Sundisc": "日轮",
      "Octomammoth": "猛犸章鱼",
      "Moldva": "莫尔巴",
      "Wahoo": "梭子鰆",
      "Raincaller": "盐烤求雨鱼",
      "Yumizuno": "弓角",
      "Zalera": "扎尔艾拉",
      "Heliobatis": "环棘鱼",
      "Toramafish": "特拉玛豹鱼",
      "Stormdancer": "招雨王",
      "Goldenfin": "金鳍蝶",
      "Junkmonger": "拾荒鮟鱇",
      "Seahag": "海巫婆",
      "Aetherlouse": "以太虱",
      "Gnomefish": "沼鯥",
      "Sunsail": "太阳帆",
      "Lavalord": "熔岩王",
      "Catkiller": "飞猫杀手",
      "Warballoon": "高风水母",
      "Skyworm": "天虫",
      "Snowcaller": "求雪鱼",
      "Lungfish": "肺鱼",
      "Hotrod": "热破",
      "Coelacanth": "腔棘鱼",
      "Nautilus": "鹦鹉螺",
      "Inkfish": "水墨鱼",
      "Cirrostratus": "卷层云魟",
      "Flarefish": "核爆鱼",
      "Hailfinder": "吞冰水母",
      "Dimorphodon": "双型齿翼龙",
      "Magma Worm": "熔岩蠕虫",
      "Granite Crab": "花岗蟹",
      "Jacques the Snipper": "剪刀手雅克",
      "Goby Ball": "虾虎丸子",
      "Star Cotton Boll": "星棉",
      "Brown Mushroom": "棕菇",
      "Teak Log": "柚木原木",
      "Magic Carpet": "魔毯",
      "Void Bass": "虚无鲈",
      "Spoon Worm": "单环刺螠",
      "Iron Noose": "铁索",
      "Marrow Sucker": "净髓蜗牛",
      "Syrphid Basket": "花蝇",
      "Floating Boulder": "浮游石",
      "Bass Ball": "鲈鱼丸子",
      "Ala Mhigan Fighting Fish": "斗鱼",
      "King of the Spring": "温泉王",
      "Shark Tuna": "金枪鲨",
      "Son of Levin": "雷皇子",
      "Caddisfly Larva": "石蚕",
      "Faerie Queen": "仙后鲈",
      "Herring Ball": "鲱鱼丸子",
      "Meteor Survivor": "陨石幸存者",
      "Rat Tail": "沟鼠尾巴",
      "Vip Viper": "大蛇鳗",
      "Mud Pilgrim": "朝圣泥鱼",
      "Merlthor Goby": "梅尔托尔虾虎",
      "The Assassin": "终结者",
      "Old Softie": "垂暮蝲蛄",
      "The Drowned Sniper": "沉溺射手",
      "Snurble Fly": "毛球拟饵",
      "Stem Borer": "蛀虫",
      "Old Hollow Eyes": "虚空之眼",
      "Carp Diem": "倔强鲫鱼",
      "Crow Fly": "乌鸦拟饵",
      "The Matriarch": "一家之母",
      "Abalathian Smelt": "阿巴拉提亚公鱼",
      "The Salter": "浓盐鲀",
      "Joan of Trout": "圣鳟贞德",
      "Pill Bug": "潮虫",
      "Harbor Herring": "海港鲱",
      "Helmsman's Hand": "翻舵手",
      "Ocean Cloud": "海云水母",
      "The Gobfather": "刺鱼教父",
      "Daniffen's Mark": "圣人标",
      "The Terpsichorean": "丽舞蟹",
      "The Captain's Chalice": "船长圣杯",
      "Dawn Maiden": "黎明少女",
      "Lamp Marimo": "绿灯球藻",
      "Chocobo Fly": "陆行鸟拟饵",
      "Frilled Shark": "皱鳃鲨",
      "Giant Squid": "巨型乌贼",
      "High Perch": "高刺鱼",
      "Sinking Minnow": "下沉诱饵鱼",
      "Mud Golem": "泥巨蟹兵",
      "The Sinker": "沉川鲑",
      "Matron Carp": "圣母鲤",
      "Blue Widow": "蓝寡妇",
      "Floating Minnow": "漂浮诱饵鱼",
      "Dark Ambusher": "暗兵鳢",
      "Moth Pupa": "蛾蛹",
      "Striped Goby": "斑纹虾虎",
      "Blood Red Bonytongue": "血红龙",
      "Common Sculpin": "杜父鱼",
      "Beguiler Chub": "无赖王",
      "Ghost Carp": "人面鲤",
      "Dirty Herry": "肮脏鲱",
      "Charon's Lantern": "冥河灯",
      "The Greatest Bream in the World": "比阿纳可大帝",
      "Shrimp Cage Feeder": "小虾肉笼",
      "The Green Jester": "绿小丑",
      "Worm of Nym": "尼姆蠕虫",
      "Crystal Perch": "水晶刺鱼",
      "The Lone Ripper": "孤独杀手",
      "Heavy Steel Jig": "重铁板钩",
      "Gigant Clam": "大愿贝",
      "Dream Goby": "梦幻虾虎",
      "Crayfish Ball": "蝲蛄丸子",
      "Navigator's Brand": "海神剑",
      "Slime King": "滑溜帝王",
      "Sabertooth Cod": "剑齿鳕",
      "The Old Man in the Sea": "海中老人",
      "Ogre Barracuda": "魔梭鱼",
      "Blue Corpse": "蓝尸",
      "Wootz Knifefish Zenith": "乌兹刀背鱼·天极",
      "Ignus Horn": "炼狱火角",
      "The Warden's Wand": "太阳神杖",
      "Magicked Mushroom": "魔幻蘑菇蟹",
      "Titanic Sawfish": "锯鲛",
      "Dark Knight": "暗骑士",
      "Amber Salamander": "琥珀蝾螈",
      "Bubble Eye": "凸眼金鱼",
      "Dravanian Squeaker": "倒仰鲶鱼",
      "Glacier Core": "冰川核",
      "Sorcerer Fish": "黑巫鱼",
      "Purse Web Spider": "土蜘蛛",
      "Armored Catfish": "鳞鲶",
      "Mountain Kraken": "妖祸克拉肯",
      "Oliphant's Trunk": "古象鼻鱼",
      "Fleece Stingray": "棉云魟",
      "Goblin Bass": "哥布林鲈",
      "Coerthan Clione": "库尔札斯海若螺",
      "Berserker Betta": "狂斗鱼",
      "Vampiric Tapestry": "吸血魔毯",
      "Jeweled Jellyfish": "宝石水母",
      "Oil Eel": "油鳗",
      "Moogle Spirit": "飞灵",
      "Blood Skipper": "鲜血跳鱼",
      "Euphotic Pirarucu": "真光层巨骨舌鱼",
      "Albino Octopus": "白章鱼",
      "Brown Bolo": "褐飞刀",
      "Magma Louse": "岩浆虱",
      "Rime Eater": "食冰水母",
      "Mercy Staff": "冰神鱼",
      "Coerthan Puffer": "山地鲀",
      "Storm Core": "风暴核",
      "Kissing Fish": "亲吻鱼",
      "Grass Carp": "草鱼",
      "Giant Donko": "大钝甲鱼",
      "Cadaver Carp": "腐鱼",
      "Rainbow Spoon Lure": "彩虹勺形鱼饵",
      "Mushroom Crab": "蘑菇蟹",
      "Judgment Staff": "雷神鱼",
      "Rock Lobster": "海岩龙虾",
      "Thunderbolt Sculpin": "雷纹鱼",
      "Paglth'an Discus": "帕戈尔赞盘丽鱼",
      "The Dreamweaver": "噩梦之种",
      "The Soul of the Martyr": "拉塔托斯克之魂",
      "The Second One": "卷风鲨",
      "Aphotic Pirarucu": "无光层巨骨舌鱼",
      "Aether Eye": "以太之眼",
      "Ice Faerie": "冰战神",
      "Hraesvelgr's Tear": "圣龙泪",
      "Moggle Mogpom": "莫古尔古球球",
      "Allagan Bladeshark": "亚拉戈剑鲨",
      "Basking Shark": "姥鲨",
      "Bobgoblin Bass": "万事通鲈",
      "Madam Butterfly": "蝴蝶夫人",
      "Hedgemole Cricket": "蝼蛄",
      "Olgoi-Khorkhoi": "沙海肠虫",
      "Bat-o'-Nine-Tails": "吸血鞭",
      "The Thousand-year Itch": "千年殇",
      "Mahi-Mahi": "麻希鲯鳅",
      "Functional Proto-hropken": "欧洛浦肯",
      "Hundred-eyed Axolotl": "百目螈",
      "Twin-tongued Carp": "叉舌鱼",
      "Dark Sleeper": "暗塘鳢",
      "Bishopfish": "大祭司鱼",
      "Charibenet": "沙里贝涅",
      "Captain Nemo": "尼摩船长",
      "Paikiller": "猴面雀杀手",
      "Heavens Coral": "天空珊瑚",
      "Sea Butterfly": "云海蝴蝶螺",
      "Scorpionfly": "蛉蝎",
      "Ceti": "赛缇",
      "Crystal Pigeon": "水晶飞鸽",
      "Opabinia": "欧巴宾海蝎",
      "Thunderscale": "雷鳞蝾螈",
      "Riddle": "里德尔",
      "The Lord of Lords": "熔岩帝王",
      "Problematicus": "莫名熔岩鱼",
      "Fossiltongue": "化石骨舌鱼",
      "The Speaker": "能言者",
      "Armor Fish": "铠鱼",
      "Thousand Fin": "千鳍",
      "Bloodchaser": "风暴血骑士",
      "Raimdellopterus": "兰代勒翼龙",

      "Little Perykos": "小珀琉喀斯",
      "Miounnefish": "缪恩鱼",
      "Gyr Abanian Trout": "基拉巴尼亚鳟",
      "Wraithfish": "幽灵鱼",
      "Falling Star": "小流星",
      "Nirvana Crab": "涅槃蟹",
      "Steelshark": "白钢鲨",
      "Deemster": "裁定鱼",
      "Bull's Bite": "猛牛口食",
      "Rock Saltfish": "岩盐咸鱼",
      "Liopleurodon": "鳍龙",
      "Ruby Shrimp": "红玉虾",
      "Tawny Wench Shark": "大天竺鱼",
      "Swordfish": "剑旗鱼",
      "Longhair Catfish": "长须鲶鱼",
      "Seraphim": "天女鱼",
      "Pandamoth": "熊猫蝶尾鱼",
      "Silken Koi": "绢鲤",
      "Doman Grass Carp": "无二草鱼",
      "Raitonfish": "雷遁鱼",
      "Killifish": "青鳉",
      "Hak Bitterling": "哈克苦鱼",
      "Hanatatsu": "花海马",
    },
    hunts: {
      "The Garlok": "伽洛克",
      "42 - 48h CD (maint. 21 - 29h)": "42-48h CD（维护后 21-29h）",
      "200m of dry weather after showers or rain.": "现实时间 200 分钟不下雨",
      "Zona Seeker": "虚无探索者",
      "Glimmerscale": "铜镜",
      "58 - 68h CD (maint. 35 - 41h)": "58-68h CD（维护后 35-41h）",
      "Catch a Glimmerscale.": "钓上铜镜",
      "Thousand-Cast Theda": "千竿口花希达",
      "Judgeray": "审判鳐",
      "Catch a Judgeray.": "钓上审判鳐",
      "Croakadile": "咕尔呱洛斯",
      "50h CD (maint. 30h)": "50h CD（维护后 30h）",
      "First day of full moon after 5PM ET.": "满月的第一天 ET 17 点之后",
      "Mindflayer": "夺心魔",
      "Midnight during new moon.": "新月期间的午夜",
      "Laideronnette": "雷德罗巨蛇",
      "43 - 48h CD (maint. 25 - 29h)": "43-48h CD（维护后 25-29h）",
      "After 10 Eorzean hours of rain (two cycles.)": "连续下雨 10 艾欧泽亚小时（两个天气周期）",
      "Gandarewa": "刚德瑞瓦",
      "80 - 132h CD (maint. 80h)": "80-132h CD（维护后 80h）",
      "Gather Seventh Heaven or Aurum Regis Ore.": "采集星极花或者皇金矿",
      "Okina": "巨大鳐",
      "?h CD (maint. ?h)": "?h CD（维护后 ?h）",
      "Full moon": "满月",
    },
    golds: {
      "Event Stage GATE": "机遇任务 - 舞台表演",
      "Side Stage GATE": "机遇任务 - 周边活动",
      "The Time of My Life, Any Way the Wind Blows": "舞蹈大师的特训 / 喷风中的幸存者",
      "Cliffhanger, Vase Off, Skinchange We Can Believe In": "小雏鸟的营救者 / 从天而降的送货人 / 火眼金睛的追踪者",
      "Josselin's Spire": "Josselin's Spire",
      "Piralnaut": "Piralnaut",
      "The Grey Fleet": "The Grey Fleet",
      "Trachtoum": "Trachtoum",
      "Highbridge": "Highbridge",
      "Helmhart": "Helmhart",
      "Dunstan's Spire": "Dunstan's Spire",
      "Marcette": "Marcette",
      "Adders' Nest": "Adders' Nest",
      "Vorsaile Heuloix": "Vorsaile Heuloix",
      "Hall of Flames": "Hall of Flames",
      "Swift": "Swift",
      "Maelstrom Command": "Maelstrom Command",
      "R'ashaht Rhiki": "R'ashaht Rhiki",
      "Apkallu Falls": "Apkallu Falls",
      "Noes": "Noes",
      "Weavers' Guild": "Weavers' Guild",
      "Yellow Moon": "Yellow Moon",
      "Lominsan Ferry Docks": "Lominsan Ferry Docks",
      "Wawalago": "Wawalago",
      "Arrzaneth Ossuary\r\n(Thaumaturges' Guild)": "Arrzaneth Ossuary\r\n(Thaumaturges' Guild)",
      "Yayake": "Yayake",
      "Cloud Nine": "Cloud Nine",
      "Gibrillont": "Gibrillont",
      "Tailfeather": "Tailfeather",
      "Marcechamp": "Marcechamp",
      "The Rosehouse": "The Rosehouse",
      "Marielle": "Marielle",
      "Matter Conduit VI-VII": "Matter Conduit VI-VII",
      "Idle Imperial": "Idle Imperial",
      "The Jeweled Crozier": "The Jeweled Crozier",
      "Elaisse": "Elaisse",
      "Dominiac": "Dominiac",
      "Laniaitte": "Laniaitte",
      "Voracious Vath": "Voracious Vath",
      "Freewalks Roundspot": "Freewalks Roundspot",
      "Seika": "Seika",
      "Entrance Square": "Entrance Square",
      "Lewena": "Lewena",
      "Ok' Gundu Nakki": "Ok' Gundu Nakki",
      "Linu Vali": "Linu Vali",
      "Vath Deftarm": "Vath Deftarm",
      "Saint Coinach's Find": "Saint Coinach's Find",
      "Klynthota": "Klynthota",
      "Bigwest Shortstop": "Bigwest Shortstop",
      "Tapklix": "Tapklix",
      "House Fortemps Manservant": "House Fortemps Manservant",
      "Bahrr Lehs": "Bahrr Lehs",
      "Master Mogzin": "Master Mogzin",
      "The Aftcastle": "The Aftcastle",
      "O'kalkaya": "O'kalkaya",
      "The Seventh Sage": "The Seventh Sage",
      "Mordyn": "Mordyn",
    },
  })),
};

(function () {
  function transform(obj, field, transformer) {
    obj[field] = eval(`(${transformer(obj[field].toString())})`);
  }

  transform(gt.bell, 'isFiltered', code => code
    .replace(/([\w.]+)(\.toLowerCase\(\))/g, 'gt.locale.translate($1)$2')
    .replace('(query && query.length > 1)', '(query)')
  );

  gt.bell.searchInput = window._.debounce(gt.bell.searchInput, 300);

  ['initializeDisplay', 'reactivateTimers', 'timerListHeaderClicked'].forEach(field => {
    transform(gt.bell, field, code => code
      .replace(`'Timers'`, `gt.t('Timers')`)
    );
  });

  gt.bell.nodes.find(x => x.title === 'Doma').time[0] = 20;
  gt.bell.nodes.find(x => x.title === 'Unseen Spirits Laughing').time[0] = 16;
})();
